FROM node:20-slim AS builder
RUN npm config set legacy-peer-deps true
COPY . .
RUN npm i
WORKDIR /front
RUN npm i
WORKDIR /
RUN npm run build_front

FROM nginx:alpine-slim
COPY --from=builder /front/build /front/build
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
