FROM node:20-slim AS builder
RUN npm config set legacy-peer-deps true
COPY . .
RUN npm i
WORKDIR /front
RUN npm i
WORKDIR /
RUN npm run build_front

FROM nginx:alpine-slim
COPY --from=builder /front/build /front/build
RUN chmod -R 755 /front/build/.
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
ENTRYPOINT ["echo", "😎 front is on http://localhost and backend endpoint is on port 4000 http://localhost:4000"]
CMD ["nginx", "-g", "daemon off;"]
