FROM node:20-slim
RUN npm config set legacy-peer-deps true
WORKDIR /app
COPY package.json .
RUN npm i
WORKDIR /app/back
COPY package.json .
RUN npm i
COPY . .
RUN npm run build_back
COPY ./back/build .
RUN npm i
EXPOSE 4000
CMD ["node", "index.js"]
